from __future__ import annotations
from pathlib import Path

def listado(items: list[dict], key: str = "name") -> str:
    return "\n".join(f"- {item.get(key) or item.get('path')}" for item in items) if items else "Sin evidencia disponible."
def flujo(flow: dict) -> str:
    return f"- **{flow['name']}** ({flow['status'].lower()}): " + " → ".join(step["name"] for step in flow["steps"])
def render(context: dict) -> str:
    system=context.get("system_model", {}); purpose=system.get("purpose", {}); story=system.get("project_story", {}); runtime=system.get("runtime", {})
    lines=["# KlapContext — Contexto del Proyecto", "", "## Propósito del Proyecto", purpose.get("text") or "No fue posible determinar el propósito del proyecto con confianza.", "", "## Cómo Funciona el Sistema", story.get("text") or "No fue posible determinar el comportamiento del sistema con confianza.", "", "## Modelo de Ejecución", runtime.get("description") or "Modelo de ejecución desconocido.", "", "## Puntos de Entrada", listado(system.get("entry_points", [])), "", "## Flujos Principales", "\n".join(flujo(x) for x in system.get("main_flows", [])) or "No se detectaron flujos principales con confianza.", "", "## Capacidades Principales", listado(system.get("capabilities", [])), "", "## Entradas", listado(system.get("inputs", []), "description"), "", "## Salidas", listado(system.get("outputs", []), "description"), "", "## Sistemas Externos", listado(system.get("external_systems", [])), "", "## Almacenes de Datos", listado(system.get("datastores", [])), "", "## Procesos en Segundo Plano", listado(system.get("background_processes", [])), "", "## Despliegue", listado(system.get("deployment", {}).get("files", []), "path"), "", "## Observabilidad", listado(system.get("observability", {}).get("tools", [])), "", "## Pruebas", listado(context.get("tests", []), "path"), "", "## Por Dónde Empezar", "\n".join(f"- **{x['intent']}**: {', '.join(x['paths'])}" for x in system.get("start_here", [])) or "No se detectaron recomendaciones de onboarding con confianza.", "", "## Archivos Importantes", "\n".join(f"- `{x['path']}` — {x['role']}" for x in system.get("important_files", [])) or "No se detectaron archivos importantes.", "", "## Arquitectura Técnica", f"{context['architecture'].get('style') or 'Desconocida'} ({context['architecture'].get('status','UNKNOWN').lower()})", "", "## Incertidumbres", "\n".join(f"- {x}" for x in system.get("unknowns", [])) or "No hay incertidumbres relevantes registradas.", "", "## Instrucciones para el Agente", "1. Lee este contexto antes de explorar ampliamente el repositorio.", "2. Usa Graphify MCP para preguntas de dependencias y rutas de llamadas.", "3. Consulta paths o vecinos relevantes antes de abrir muchos archivos.", "4. Lee el código real antes de modificarlo.", "5. Trata el contexto inferido como guía, no como verdad absoluta.", "6. Prefiere los tests y puntos de entrada relevantes identificados por KlapContext."]
    text="\n".join(lines).rstrip()+"\n"; return text+f"\nTokens estimados: {max(1, len(text.split()) * 4 // 3)}\n"
def write(context: dict, output: Path) -> str:
    text=render(context); output.write_text(text, encoding="utf-8"); return text
